config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :members

  scope module: :member do
    get 'mypage' => 'mypage#index'

    resources :members, only: [:show] do
      get 'new_answers'
      patch 'create_answers'
    end
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :member
  belongs_to :question

  # validates :score, presence: true
  # validates :body, presence: true

  scope :mine, -> (member) {
    where(member_id: member.id)
  }

end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :need_answer_members, class_name: :NeedAnswerMember, foreign_key: :from_member_id
  has_many :to_members, through: :need_answer_members
  has_many :wait_answer_list, class_name: :NeedAnswerMember, foreign_key: :to_member_id
  has_many :answers
  accepts_nested_attributes_for :answers

  def summary_score
    sql = "
      select
      	to_char(created_at, 'YYYY-MM') date
      	,avg(score) average
      	,(coalesce(sum(case when score >= 9 then 1 end), 0) - coalesce(sum(case when score <= 6 then -1 end), 0)) * 100 / count(*) nps
      from
      	answers
      where
      	member_id = #{self.id}
      	and score is not null
      group by
      	to_char(created_at, 'YYYY-MM')
      order by 1 desc
    "
    Answer.find_by_sql(sql)
  end

end

app/models/need_answer_member.rb
class NeedAnswerMember < ActiveRecord::Base
  belongs_to :from_member, class_name: :Member, foreign_key: :from_member_id
  belongs_to :to_member, class_name: :Member, foreign_key: :to_member_id
end

app/models/question.rb
class Question < ActiveRecord::Base

  belongs_to :answer
  has_many :answers

  enum question_type: {
    text: 1,
    radio_5: 2,
  }
  USE_TYPE_LABELS = {
    "自由入力" => :text,
    "５段階評価" => :radio_5,
  }

  attr_accessor :my_answers

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    mypage_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/member/app_controller.rb
class Member::AppController < ApplicationController
  prepend_before_action :authenticate_member!
end

app/controllers/member/members_controller.rb
class Member::MembersController < Member::AppController
  def new_answers
    @member = Member.find_by_id(params[:member_id])
    Question.all.each do |q|
      @member.answers.build(question: q)
    end
  end

  def create_answers
    answers = []
    create_answers_params[:answers_attributes].to_h.values.each do |answer_param|
      answers << Answer.new(answer_param.merge({member_id: params[:member_id]}))
    end

    validate = true
    answers.each do |answer|
      validate = answer.validate
    end

    if validate
      ActiveRecord::Base.transaction do
        Answer.import answers
        NeedAnswerMember.where(from_member: current_member)
          .where(to_member: params[:member_id]).delete_all
      end
      redirect_to mypage_path, notice: "回答を入力しました"
    else
      new_answers
      flash[:notice] = "入力必須です"
      render :new_answers
    end
  end

  def show
    @questions = Question.all.each do |q|
      q.my_answers = current_member.answers.where(question_id: q.id).order("id DESC")
    end
    @my_scores = current_member.summary_score
  end

  private
    def create_answers_params
      params[:member].permit(answers_attributes: [:question_id, :score, :body])
    end
end

app/controllers/member/mypage_controller.rb
class Member::MypageController < Member::AppController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.haml
%h1
  ITANDI geist

%h2 ログイン

= form_for :member, url: member_session_path do |f|
  %fieldset
    %label メール
    = f.email_field :email, placeorder: "geist@itandi.co.jp"
  %fieldset
    %label パスワード
    = f.password_field :password

  %fieldset
    %label ログインキープ
    = f.check_box :remember_me

  %fieldset
    %label ログイン
    = f.submit "sign in"

  = link_to "Forgot your password?", new_member_password_path

app/views/layouts/application.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Geist"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    = stylesheet_link_tag "application", :media => "all"
    / For third-generation iPad with high-resolution Retina display:
    / Size should be 144 x 144 pixels
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    / For iPhone with high-resolution Retina display:
    / Size should be 114 x 114 pixels
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    / For first- and second-generation iPad:
    / Size should be 72 x 72 pixels
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    / For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    / Size should be 57 x 57 pixels
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    / For all other devices
    / Size should be 32 x 32 pixels
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
  %body
    %header
      %nav
        - if member_signed_in?
          = "こんにちは#{current_member.name}さん"
          = link_to "設定変更", edit_member_registration_path
          = link_to "ログアウト", destroy_member_session_path, method: :delete
        - else
          = link_to "新規登録", new_member_registration_path

    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield

      %footer
        %p © ITANDI .inc 2015

app/views/member/members/new_answers.haml
= flash[:notice]

%h1="#{@member.name}さんの評価を入力する"

= form_for @member, url: member_create_answers_path do |f|
  %ul
  = f.fields_for :answers do |af|
    - if af.object.id.nil?
      %li
        = af.hidden_field :question_id
        %label=af.object.question.subtitle
        %br
        - if af.object.question.text?
          = af.text_area :body, {rows: 10, cols: 80}
        - if af.object.question.radio_5?
          - (1..10).each do |n|
            %label="#{n}点"
            = af.radio_button :score, n
            %br

  = f.submit "評価を送信する"

app/views/member/members/show.haml
%h1="#{current_member.name}さんの評価"

- @questions.each do |q|
  %dl
    - if q.text?
      %dt= q.subtitle
      %dd
        %ul
          - q.my_answers.each do |a|
            %li
              = "回答月：#{a.created_at.strftime('%Y-%m')}"
              = "回答文：#{a.body}"
    - if q.radio_5?
      %dt= q.subtitle
      %dd
        %ul
          - @my_scores.each do |s|
            %li
              = "年月：#{s.date}"
              = "平均点：#{s.average.round(2)}"
              = "NPS：#{s.nps}"

app/views/member/mypage/index.haml
- if notice
  = notice

%h1 マイページ

%h2 他者への評価
- if current_member.to_members.present?
  %ul
    - current_member.to_members.each do |to_member|
      %li
        = link_to "#{to_member.name}さんの評価を回答する", member_new_answers_path(to_member)
- else
  評価対象者はいません

%h2="#{current_member.name}さんへの評価"
- if current_member.wait_answer_list.present?
  評価中です、結果集計までしばらくお待ち下さい
- elsif current_member.answers.present?
  = link_to "自分の評価集計結果を見る", member_path(current_member)
- else
  評価待ち、評価結果はありません。